### ISSUE TITLE
Get OA.org working on Ubuntu 14.04

### ISSUE THREAD

**Issue by henare** [openaustralia/openaustralia#559]
* Fix #252
* What else doesn't work?

**Comment by mattjoyce** [comment]
I could not compile Xapien on Debian.
Other thing might not work, but that was a show stopper for me.
During that adventure, I did chance upon other search engines.
Not sure how plausible abstracting the search functions, and try other
engines would be.

also, hello.

On Mon, Feb 2, 2015 at 3:43 PM, Henare Degan <notifications@github.com>
wrote:

> What doesn't work? Search? <=== Please update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaustralia/openaustralia/issues/559>.
>



-- 
+61 468 335597
*LinkedIn Profile : Matt Joyce
<http://au.linkedin.com/pub/matthew-joyce/6/4b5/6a4/>*

**Comment by henare** [comment]
Hello @mattjoyce and thank you for chiming in!

I'll track the Xapian problem on #252.

I'm leaving this ticket open until I've had a bit more of a poke around although I can't immediately think of anything else that's a problem.

**Comment by henare** [comment]
It all seems to work for me now so I'll close this.

**Comment by henare** [comment]
To get email alerts working I also had to remember to set `short_open_tag = On` and `enable_dl = On` in the php.ini for CLI, i.e. `/etc/php5/cli/php.ini`
