### ISSUE TITLE
Send emails using Cuttlefish

### ISSUE THREAD

**Issue by henare** [openaustralia/openaustralia#561]

**Comment by henare** [comment]
I was getting excited that the [code to send email](https://github.com/openaustralia/twfy/blob/master/www/includes/utility.php#L742) just uses PHP's mail() function. Alas it's PHP so:

>[PHP mail() command does not support authentication.](http://stackoverflow.com/a/112305/741049)

:unamused:

**Comment by mlandauer** [comment]
Eek!

**Comment by henare** [comment]
OK what we can do is set all PHP mail to go via Cuttlefish.

On Unix, PHP's mail() function uses `sendmail` but you can change that command. So we can configure PHP to use [msmtp](http://msmtp.sourceforge.net/), which we can configure to point at Cuttlefish.

The other PHP application on kedumba is Election Leaflets so I think this should be fine.

**Comment by mattjoyce** [comment]
Perhaps we should seperate the creating of emails, from sending of emails?
Have alertmailer.php build them, and dump them in a folder, have some other
process send them via cuttlefish.



On Fri, Feb 13, 2015 at 5:35 PM, Henare Degan <notifications@github.com>
wrote:

> OK what we can do is set all PHP mail to go via Cuttlefish.
>
> On Unix, PHP's mail() function uses sendmail but you can change that
> command. So we can configure PHP to use msmtp
> <http://msmtp.sourceforge.net/>, which we can configure to point at
> Cuttlefish.
>
> The other PHP application on kedumba is Election Leaflets so I think this
> should be fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaustralia/openaustralia/issues/561#issuecomment-74211512>
> .
>



-- 
+61 468 335597
*LinkedIn Profile : Matt Joyce
<http://au.linkedin.com/pub/matthew-joyce/6/4b5/6a4/>*

**Comment by henare** [comment]
I'm going ahead with the msmtp solution today. This will give us visibility of the emails we're sending which will really help when we deploy https://github.com/openaustralia/twfy/pull/11

**Comment by henare** [comment]
Done.

* Install `msmtp` package
* Create file `/etc/msmtprc` with contents:

```
account cuttlefish
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
host cuttlefish.oaf.org.au
port 2525
auth on
user [cuttlefish username]
password [cuttlefish password]
account default : cuttlefish
```

* Edit PHP configuration files `/etc/php5/apache2/php.ini` and `/etc/php5/cli/php.ini` and add the following line:

```
sendmail_path = "msmtp --read-envelope-from -t"
```

* Restart Apache
* Disco :dancer:
