### ISSUE TITLE
[HTML email] View other debates [person] spoken in shown below phrase results

### ISSUE THREAD

**Issue by henare** [openaustralia/openaustralia#562]
The highlighted things should not be here.
![email alerts from openaustralia org 2015-02-17 16-33-45](https://cloud.githubusercontent.com/assets/48945/6223664/e3084286-b6c2-11e4-9e0c-44df03e3e577.png)

Relates to https://github.com/openaustralia/twfy/pull/11

**Comment by mattjoyce** [comment]
Fixed, commit to follow shortly.

**Comment by mattjoyce** [comment]
Tested with an alert with multiple speakers and phrase alerts, only the speaker alerts have a link.
