### ISSUE TITLE
[HTML email] Unregistered users are told they're registered users

### ISSUE THREAD

**Issue by henare** [openaustralia/openaustralia#564]
Every HTML email says:

>You're receiving this Email Alert as a register user of OpenAustralia.org.
>Too much to read? Manage your Email alert preferences

That should only be shown for registered users. Unregistered users see this in text email:

>If you register on the site, you will be able to manage your
>alerts there as well as post comments. :)

Relates to https://github.com/openaustralia/twfy/pull/11

**Comment by henare** [comment]
@mattjoyce has this been addressed in openaustralia/twfy#11?

**Comment by mattjoyce** [comment]
Ah I see.  The original html template only has the prose for registered users.
...thinking....

**Comment by henare** [comment]
Fixed in https://github.com/openaustralia/twfy/commit/3d544af37051a241b8437c245779fff06cc43c37 assigning to me to test.

**Comment by henare** [comment]
https://github.com/openaustralia/twfy/pull/11#issuecomment-114705200 has been closed for the moment.
