### ISSUE TITLE
[HTML email] Strange characters appear in Gmail

### ISSUE THREAD

**Issue by henare** [openaustralia/openaustralia#566]
![selection_001](https://cloud.githubusercontent.com/assets/48945/6223801/4e543bba-b6c5-11e4-83ee-3dcd58497632.png)

Relates to https://github.com/openaustralia/twfy/pull/11

**Comment by henare** [comment]
`Â` seems to be showing up where `&nbsp;` is in the template and `â€”` where there's `&mdash;` in the template.

**Comment by henare** [comment]
A cursory look suggests this problem is character encoding.

**Comment by mattjoyce** [comment]
Encoding changed, please try again.

**Comment by davidjeliba** [comment]
Has this been re-tested?

**Comment by henare** [comment]
Assigned to me to test.

**Comment by henare** [comment]
https://github.com/openaustralia/twfy/pull/11#issuecomment-114705200 has been closed for the moment.
