### ISSUE TITLE
[HTML email] Yahoo mail breaking href links

### ISSUE THREAD

**Issue by mattjoyce** [openaustralia/openaustralia#567]
hrefs with a query like **?id=1&foo=2** become **?id 1&1&foo=2**, which break them.
Have tried an alternate var name.

**Comment by henare** [comment]
`id=1` becomes `id 1&1`? Very strange.

**Comment by mattjoyce** [comment]
I did more tests last night.
Id=TEST1 remains unchanged.
Haven't tied reordering var, but I will.

So we can build a workaround.


On Wednesday, 18 February 2015, Henare Degan <notifications@github.com>
wrote:

> id=1 becomes id 1&1? Very strange.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaustralia/openaustralia/issues/567#issuecomment-74773475>
> .
>


-- 
+61 468 335597
*LinkedIn Profile : Matt Joyce
<http://au.linkedin.com/pub/matthew-joyce/6/4b5/6a4/>*

**Comment by henare** [comment]
>So we can build a workaround.

It would be better if we could get to the bottom of the problem.

**Comment by mattjoyce** [comment]
I agree completely.
Just to be clear, the content we send to Yahoo has the =, yahoo is removing
it
, in some circumstances.   They also make a lot of changes to the styles
and what haveli.

The same link is fine in gmail, or my work email (exchange).



On Wednesday, 18 February 2015, Henare Degan <notifications@github.com>
wrote:

> So we can build a workaround.
>
> It would be better if we could get to the bottom of the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaustralia/openaustralia/issues/567#issuecomment-74803471>
> .
>


-- 
+61 468 335597
*LinkedIn Profile : Matt Joyce
<http://au.linkedin.com/pub/matthew-joyce/6/4b5/6a4/>*

**Comment by henare** [comment]
My wild guess would be some MIME misreading since `=` is [used for output padding](https://en.wikipedia.org/wiki/Base64#MIME) and it's all to suspicious that that is the same character we're having problems with.

**Comment by mattjoyce** [comment]
Here's a typical href which will be altered.
<a class="bluebutton" href="http://www.openaustralia.org/debates/?oaid=TEST2007-09-20.79.2&s=overboard#g92.1" style="background-color: #DCE9F8; border-radius: 5px; color: #428bca; display: inline-block; font-size: 12px; padding: 1px 5px; text-decoration: none; line-height: 18px;" target="_blank">Full debate</a>

In this case it worked, as I prefixed the value (TEST2007...).

I will try non-multipart mime to night to see if the issue manifests with straight html.

**Comment by mattjoyce** [comment]
On a more general note, I'm probably be naive when I say I'm surprised Yahoo and Gmail render the same content so completely differently.   These were just the accounts I had to had at the time.  no idea what other clients will do.

**Comment by henare** [comment]
I think @davidjeliba was running these through Litmus for that exact reason :)

**Comment by henare** [comment]
>Here's a typical href which will be altered.

I don't think it's valid that the query part is not encoded, i.e. the `&` should be `&amp;`. This could be the problem.

**Comment by mattjoyce** [comment]
Maybe, but does not explain why prefixing the numeric value with alphas,
stops the problem.

Well formed URLs seems like a good idea regardless.  I think these links
are saved in the database (not including the base host section).

Do you think we should update the database, or reformat the link before
emailing?

**Comment by henare** [comment]
>Do you think we should update the database, or reformat the link before emailing?

The link is valid in the database but when you put it in an `href` you need to encode it so I think we should just be calling the PHP function for that on the links when inserting them.

**Comment by mattjoyce** [comment]
I did try that, using urlencode().
It broke some stuff, I think the values got encoded, which broke search in
/debates/

I guess they can be decoded, before search uses them.
I'll try that.

**Comment by henare** [comment]
Sounds like the right approach.

I'm not sure what you mean by "broke search".

**Comment by mattjoyce** [comment]
One of the function of the Debate class is to search for debates.  The
encoded link used encoded search criteria, which returns no hits.
I'm speculating a bit, I didn't dig much.

**Comment by henare** [comment]
I'm still unclear on what you're referring to - probably because I don't know it was well as you :) Are you trying to encode it just before adding the link to the email or elsewhere?

**Comment by mattjoyce** [comment]
I double check later, but I think the link in the db, has parameters with
values that have characters, that become encoded. The encoded values get
passed to the search function.  I have a plan.  All good.

On Thursday, 19 February 2015, Henare Degan <notifications@github.com>
wrote:

> I'm still unclear on what you're referring to - probably because I don't
> know it was well as you :) Are you trying to encode it just before adding
> the link to the email or elsewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaustralia/openaustralia/issues/567#issuecomment-74979149>
> .
>


-- 
+61 468 335597
*LinkedIn Profile : Matt Joyce
<http://au.linkedin.com/pub/matthew-joyce/6/4b5/6a4/>*

**Comment by mattjoyce** [comment]
I sent the emails a straight html, not multipart mime, and the problem persists.

Thinking about proper encoding, this is an example of what is stored in the database.
/debates/?id=2007-09-20.67.2&s=speaker%3A10001#g68.1
htmlentities() will produce this
/debates/?id=2007-09-20.67.2&amp;s=speaker%3A10001#g68.1
Yahoo removes the first =

If I prefix the first value with OA, I get
/debates/?id=OA2007-09-20.67.2&amp;s=speaker%3A10001#g68.1
Yahoo, does not alter it.

It would be good to know why Yahoo does this, but a workaround would be to remove OA in /debates/

**Comment by mattjoyce** [comment]
Fixed.
Think it was the encoding problem.
