### ISSUE TITLE
[HTML email] GMail not rendering multipart mime messages as expected.

### ISSUE THREAD

**Issue by mattjoyce** [openaustralia/openaustralia#568]
Multipart boundaries are detected, but HTML code is visible in the HTML section.
The same email renders ok in Yahoo mail.

**Comment by henare** [comment]
I don't see any HTML code, just lots of `Â` characters and stuff: #566

**Comment by henare** [comment]
@mattjoyce as per my previous comment, I can't reproduce this. Can you provide more details?

**Comment by mattjoyce** [comment]
Here the view from my window...https://imgur.com/HTwd1bs
As you can see the text portion is showing, and html is not rendered.

This was Windows+Chrome...
....same for Linux+Chrome....


On Fri, Feb 20, 2015 at 11:46 AM, Henare Degan <notifications@github.com>
wrote:

> @mattjoyce <https://github.com/mattjoyce> as per my previous comment, I
> can't reproduce this. Can you provide more details?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openaustralia/openaustralia/issues/568#issuecomment-75170211>
> .
>



-- 
+61 468 335597
*LinkedIn Profile : Matt Joyce
<http://au.linkedin.com/pub/matthew-joyce/6/4b5/6a4/>*

**Comment by mattjoyce** [comment]
OK, we were not on the same code.   Now I have my GIt sorted out, I can see the code your running is only sending html, not multipart mime.

**Comment by mattjoyce** [comment]
This has been muchly improved by changing encoding.  (Just as you said @henare!).
