### ISSUE TITLE
Find out results of survey and remove survey banners

### ISSUE THREAD

**Issue by henare** [openaustralia/openaustralia#588]

**Comment by equivalentideas** [comment]
I've emailed the mySoc team running the survey to find out where it's at.

**Comment by henare** [comment]
@equivalentideas any word from them?

I think we should go ahead and remove the banners. Presumably they were removed months ago on TWFY and one of [their findings](https://www.mysociety.org/2015/11/04/understanding-theyworkforyous-users-without-the-power-of-mind-reading/) was, "_People hate pop-ups_" so I don't see why we should annoy people using our sites any longer.

The reason I keep coming back to this is because I see them on OA.org and they're annoying! :smile:

**Comment by equivalentideas** [comment]
> I think we should go ahead and remove the banners. Presumably they were removed months ago on TWFY and one of their findings was, "People hate pop-ups" so I don't see why we should annoy people using our sites any longer.

I agree, I'm gonna revert the two PRs for the two experiments now:

* https://github.com/openaustralia/twfy/pull/14
* https://github.com/openaustralia/twfy/pull/13

**Comment by equivalentideas** [comment]
Those reverts work, going to finish it in the morning though. The commit message you get from reverting a merge in Github is really crap, which makes me think about things that make my brain squirm right now. I’ll sure I’ll be happy to just it merge in the morning :D

**Comment by equivalentideas** [comment]
Those reverts were merged and we got the survey results in email so I'll close this.
