### ISSUE TITLE
Twitter data missing

### ISSUE THREAD

**Issue by drzax** [openaustralia/openaustralia#591]
The XML file at http://data.openaustralia.org/members/twitter.xml which presumably holds a mapping of Twitter account ⟺ MP appears to be empty or truncated.

**Comment by henare** [comment]
Thanks for raising this @drzax, I've had a look into it.

It's not [used any more](https://github.com/openaustralia/twfy/commit/a11172b4eca97b8d348a788e5c4be2ba759a7cdf). The twitter info comes from [a morph.io scraper](https://morph.io/openaustralia/aus_mp_contact_details/) and is [parsed into](https://github.com/openaustralia/openaustralia-parser/blob/master/parse-member-links.rb#L25-L35) the `websites.xml` file.

If you're looking for this information I'd go with http://everypolitician.org/australia/ as the most up to date and comprehensive source.

**Comment by drzax** [comment]
Thanks @henare. Does the Every Politician data come from OA data?

**Comment by henare** [comment]
By and large but I'd consider it a super-set.

**Comment by henare** [comment]
I also forgot to mention I've removed the file from our server so it's less confusing for the next person.
