### ISSUE TITLE
Incorrect Hansard reference link (and/or wrong date) 

### ISSUE THREAD

**Issue by brtrx** [openaustralia/openaustralia#593]
Looking at this debate on OA.org, I went to Hansard to see if there was a related Division.
http://www.openaustralia.org.au/debates/?id=2016-02-08.146.2 
![image](https://cloud.githubusercontent.com/assets/8436356/14226385/f8326414-f8e0-11e5-8cb5-acb76612b352.png)

The link led me here 
http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A8%2F2%2F2016;rec=0;resCount=Default
which seems to be the correct date (8/2/2016), but there's no Private Members Bill debate involving the topic Domestic Violence, or the member Bruce Billson at this time.

The closest I could find to the time indicated on OA.org was the one below, which as you can see is a comment by Gary Gray on mining.
http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;db=CHAMBER;id=chamber%2Fhansardr%2Fa8ddabc5-4310-4bda-a2fd-c9e6a54e12dc%2F0051;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A8%2F2%2F2016;rec=0;resCount=Default
![image](https://cloud.githubusercontent.com/assets/8436356/14226393/55f6dd96-f8e1-11e5-9725-561debb2c9d4.png)

**Comment by henare** [comment]
ParlInfo is a nightmare :scream: That debate was below "Federation Chamber" on that page:

http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;db=CHAMBER;id=chamber%2Fhansardr%2Fa8ddabc5-4310-4bda-a2fd-c9e6a54e12dc%2F0252;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A8%2F2%2F2016;rec=0;resCount=Default

I might be biased but They Vote For You is also a rather good place to check for division :wink: 

https://theyvoteforyou.org.au/divisions/representatives/2016-02-08

**Comment by brtrx** [comment]
Actually, I was looking through OA and through Hansard, because I couldn't find a single division in TVFY concerning domestic violence, or even women, for the last 2 years. 

Why doesn't the Hansard link in OA point directly to that first speech, or to the debate starting point http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;db=CHAMBER;id=chamber%2Fhansardr%2Fa8ddabc5-4310-4bda-a2fd-c9e6a54e12dc%2F0251;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A8%2F2%2F2016;rec=0;resCount=Default?

Would it be appropriate to raise this as a separate issue? A similar link is used in TVFY. That should be it's own issue, but I assume it's dependent on something changing here.

**Comment by brtrx** [comment]
Ok, I had a look at http://data.openaustralia.org/scrapedxml/representatives_debates/2016-02-08.xml
and now I see what you mean about ParlInfo. :scream:

**Comment by henare** [comment]
>Why doesn't the Hansard link in OA point directly to that first speech, or to the debate starting point http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;db=CHAMBER;id=chamber%2Fhansardr%2Fa8ddabc5-4310-4bda-a2fd-c9e6a54e12dc%2F0251;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A8%2F2%2F2016;rec=0;resCount=Default?
>
>Would it be appropriate to raise this as a separate issue? A similar link is used in TVFY. That should be it's own issue, but I assume it's dependent on something changing here.

Yep, that issue is #289.
