### ISSUE TITLE
Update postcode lookup for 2016 boundaries

### ISSUE THREAD

**Issue by coagmano** [openaustralia/openaustralia#594]
I'm using the OA API for a tool to find candidates based on postcode this election, and the postcode -> electorate mapping is still using the old boundaries. 
[Is this the data used by the API](https://github.com/openaustralia/openaustralia-parser/blob/master/data/postcodes.csv)

This creates a new problem. The old boundaries remain in effect till the election and searches for current electorate should return results they do now. But searches relating to the election (which electorate will my vote count towards, which candidates are in my electorate) should use the new distribution.

I'm happy to create the postcode map under the new distribution and provide, but it seems as though we need a new endpoint (or parameter) to search for electorate at the next election?

I also need to know at what amount of overlap do we say a postcode is in an electorate, 5%? 10%? 25%?

**Comment by henare** [comment]
Thanks for opening this issue @coagmano :ok_hand: 

> Is this the data used by the API

Yes, created by [this scraper](https://github.com/openaustralia/openaustralia-parser/blob/master/parse-postcodes.rb). It's important that people are able to recreate the data using something open like that.

>I'm happy to create the postcode map under the new distribution and provide, but it seems as though we need a new endpoint (or parameter) to search for electorate at the next election?

The API already has the date parameter for this: http://www.openaustralia.org.au/api/docs/getDivisions

>I also need to know at what amount of overlap do we say a postcode is in an electorate, 5%? 10%? 25%?

I don't quite understand what you mean. Maybe check the existing data & scraper to see how it works currently?

**Comment by coagmano** [comment]
> Thanks for opening this issue @coagmano :ok_hand:
> 
> > Is this the data used by the API
> 
> Yes, created by this scraper. It's important that people are able to recreate the data using something open like that.

So I need to find out if the AEC have updated the data behind their search

> > I'm happy to create the postcode map under the new distribution and provide, but it seems as though we need a new endpoint (or parameter) to search for electorate at the next election?
>
> The API already has the date parameter for this: http://www.openaustralia.org.au/api/docs/getDivisions

Awesome, I didn't realise that. That makes this much easier. Hooray for forward thinking!

> > I also need to know at what amount of overlap do we say a postcode is in an electorate, 5%? 10%? 25%?
>
> I don't quite understand what you mean. Maybe check the existing data & scraper to see how it works currently?

I was planning on making a spreadsheet using the GIS map-files, but that's harder to automate without infrastructure. Because postcode and electoral division overlaps can be anywhere between 1% and 100%, you need to set a point at which you decide that a postcode is actually within an electorate and should return that electorate in search results.

I'm thinking I'll just run the existing scraper and compare the data with the 2010 data already in the repo and the list I've got based off GIS data. Then I'll be able to tell if the current AEC results are including the new boundaries or not and if the scraper needs any work.

One simple question, "Does that search include the new boundaries" has turned into a bunch of work haha 😭

**Comment by henare** [comment]
I think @drzax's scraper contains the data we want https://morph.io/drzax/morph-division-postcode-correspondence

**Comment by henare** [comment]
I just noticed that The Greens do the lookup right in the JavaScript on this page http://greens.org.au/candidates/all. I wonder where they got the data? I've saved a copy https://gist.github.com/henare/3ecb8868b426d73b493fc12302389371

**Comment by archoo** [comment]
that looks like a raw dump of the ABS Postal Area to CED concordance, but more up to date than the one posted on the abs site.. 

Any organisation who has the financial resources to procure the AustPost postcode dataset could quite easily to a spatial query to generate that dataset.. it is a simple polygon intersect query.. giving all Post Codes that overlap an electorate boundary.. 

Unfortunately, unless AustPost change their mind.. the ABS postal area layer is the closest us plebs will get to an accurate polygon of the up to date postcode database.. :(

**Comment by archoo** [comment]
hmmm.. just had a thought.. gnaf has spatial locations for all physical addresses and for some reason the PSMA chose to keep the postcode in the address (it normally isn't officially part of the location dataset).. this has potential.. especially if all that is required is a list of "electorate" -> "postcode" mappings.. i shall investigate..

**Comment by drzax** [comment]
That would be a fairly serious query, but I fell like it would work.


On 14 June 2016 at 21:23:04, Daniel Hoolihan (notifications@github.com)
wrote:

hmmm.. just had a thought.. gnaf has spatial locations for all physical
addresses and for some reason the PSMA chose to keep the postcode in the
address (it normally isn't officially part of the location dataset).. this
has potential.. especially if all that is required is a list of
"electorate" -> "postcode" mappings.. i shall investigate..

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openaustralia/openaustralia/issues/594#issuecomment-225852595>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAkaU4lGMtNaRqkGz-iFV2Kcj11XvVCRks5qLo8YgaJpZM4IF7H2>
.

**Comment by archoo** [comment]
agreed.. and while i have gnaf nicely loaded in oracle.. the XE version doesn't support spatial.. so time to do some serious research on mysql/postgres spatial optimisation.. or call in some favours.. :)
