### ISSUE TITLE
Display social media and website information for representatives where available

### ISSUE THREAD

**Issue by brtrx** [openaustralia/openaustralia#598]
Dependent on #592, i.e. once this information is available

Objective: Identify where and how to display a representative's social media and website information.

Constraint: On the representative profile pages, it may be easy to confuse their social media information with our social sharing buttons.

**Comment by brtrx** [comment]
Based on data here: http://data.openaustralia.org/members/websites.xml
We have access to:

1. Parliament House web page (ALL)
2. Parliament House contact page (ALL)
3. Email (SOME)
4. Twitter account (SOME)
5. Website (SOME)

For example, for Tanya Plibersek, we have access to:

1. Parliament House web page: http://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=83M
2. Parliament House contact page: http://www.aph.gov.au/Senators_and_Members/Contact_Senator_or_Member?MPID=83M
3. Twitter account: http://twitter.com/tanya_plibersek
4. Website: http://www.tanyaplibersek.com/

**Comment by henare** [comment]
@brtrx we already display this:

![tanya plibersek mp sydney openaustralia org - mozilla firefox_001](https://cloud.githubusercontent.com/assets/48945/16324633/6b866d44-39f9-11e6-8a5b-e4eccdadd5b1.png)

But I'd guess you're not the only one to miss that! :smiley: Should we make this issue about improving the display of that?

I've always thought this is really interesting and useful information. Interestingly our sister site in the UK doesn't display links like this very prominently either, e.g. http://www.theyworkforyou.com/mp/10777/david_cameron/witney#profile

**Comment by brtrx** [comment]
My mistake, I got my repositories mixed up. I thought we were talking about They Vote For You.
FWIW, I was about to say there's no link to the OA information on TVFY, but then I discovered that "Speeches in Parliament" is the link. I'll close this issue, and open a new one in the other repository.
