### ISSUE TITLE
Wrong MP image downloaded

### ISSUE THREAD

**Issue by henare** [openaustralia/openaustralia#600]
Pauline Hanson's image is actually Sarah Hanson-Young! http://www.openaustralia.org.au/mp/pauline_hanson/oxley

I've deleted the image for the moment. I don't think the member image download process happens automatically so it shouldn't revert. We'll need to fix it before we run it again though.

**Comment by equivalentideas** [comment]
This is occurring because when `member-images.rb` runs and gets to Sarah Hanson Young, it overrides the image for Pauline Hanson and saves a new image. Now, to work out why?

**Comment by equivalentideas** [comment]
Ok, so I've been digging about and have discovered that this is actually a problem with the parsing of names in the format "  HANSON  -  YOUNG  ,   Sarah   Coral", in the image downloader.

Our parser can't handle hyphenated last names. This isn't a problem unless the resulting last name "Hanson" in this case matches another MPs last name.

I'm adding test coverage for the offending method and I'll fix it.
