### ISSUE TITLE
alerts bring up old quotes first then new

### ISSUE THREAD

**Issue by wwwalker** [openaustralia/openaustralia#621]
I am getting alerts for 29/11/16 instead of 27/2/17 for example for Andrew Gee or Peter Dutton or Tanya Plibersek or George Christensen.

Surely the order of alerts should be latest quotes first then oldest i.e. order date descending.

I can find latest quotes by searching on the Website but it would be nice for the alerts to display the last 5 latest quotes in descending order not the ones back 3 months ago first and having to search on Website for latest ones.

This happens for all my alerts except for Malcolm Turnbull and Bill Shorten etc and others whom I have been following for a while.

The ones with old quotes I added may be a month ago to my alerts.

May be this is a bug re adding a new alert and it is catching up. I don't know.

May be fixing 29/11/16 has screwed up the alerts for later debates and no other dates are being alerted on.

**Comment by henare** [comment]
Hi @wwwalker thanks for reporting this! Did you just get one email alert with a bunch of old speeches?

**Comment by wwwalker** [comment]
Yes.

> Hi @wwwalker thanks for reporting this! Did you just get one email alert
> with a bunch of old speeches?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/openaustralia/openaustralia/issues/621#issuecomment-284958356


-- 
Dwight Walker
WWWalker Web Development Pty Ltd
www.wwwalker.com.au

**Comment by henare** [comment]
Thanks. It was just a mistake on my part then. I didn't think reloading these debates would mean new emails would be sent. I should have done [this magic](https://github.com/openaustralia/openaustralia/wiki/Email-alert-tasks#skipping-email-alerts) to make sure alerts weren't sent for these re-parsed days.
