### ISSUE TITLE
Senator Gavin Marshall is not the Senate Deputy President, Sue Lines is

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/openaustralia#622]
http://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=00AOP

http://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=112096

Thanks to FlickRubicon for telling us https://twitter.com/FlickRubicon/status/862500667637628928

Update following instructions here https://github.com/openaustralia/openaustralia-parser#ministerial-reshuffles

**Comment by MicaelaMicaela** [comment]
Hi @equivalentideas - I went in to make this change but can't find Gavin Marshall listed at all in either  data/ministers.csv or data/shadow-ministers.csv and didn't want to add Sue Lines until I can find where Marshall is...

**Comment by MicaelaMicaela** [comment]
found it! Marshall Deputy President-ness is listed in data/senators.csv - just created pull request!
