### ISSUE TITLE
Most of OpenAustralia API could be made redundant by a simple DB dump

### ISSUE THREAD

**Issue by jnothman** [openaustralia/openaustralia#630]
OpenAustralia should be a reliable data resource on politicians and their history for projects like http://everypolitician.org/. But currently the API is very limited. It does not, for instance, list current or past ministries held by a person, even though this data is present in the database.

The database of politicians (ignoring user comments, hansard, etc.) cannot be more than a megabyte or so total in size, so an API is not really necessary to access it as long as it is dumped in a usable format. I would argue that it is much easier to maintain a database snapshot: dump all relevant tables nightly and push any changes to a repository on github. Users can do the table joins and selects themselves.

**Comment by mlandauer** [comment]
@jnothman all of the data that drives http://www.openaustralia.org.au/ is also available as a data dump at http://data.openaustralia.org/

**Comment by jnothman** [comment]
Okay, I had not been aware that was there. Thanks. Perhaps unused ministers and other files should be removed from https://github.com/openaustralia/openaustralia-parser/tree/master/data as they are red herrings...

**Comment by jnothman** [comment]
Also, I still think that having http://data.openaustralia.org/members/ git-revisioned would be a boon.

**Comment by mlandauer** [comment]
@jnothman if it's versioned members data you want then have a look at https://github.com/openaustralia/openaustralia-parser/tree/master/data

**Comment by jnothman** [comment]
Okay. I'm being silly. Versioning is unnecessary seeing as most of the data is timestamped and you can get the last-updated timestamp per file from the HTTP server.

But https://github.com/openaustralia/openaustralia-parser/tree/master/data includes files that are not useful, notably `shadow-ministers.csv` and `ministers.csv`
