### ISSUE TITLE
hansard missing for 16/11/17

### ISSUE THREAD

**Issue by wwwalker** [openaustralia/openaustralia#631]
Hansard is missing for 13-16/11/17

http://www.openaustralia.org.au/debates/?y=2017

Maybe cache has to be cleared and import re-run like before when dates were missing.

This is about Marriage Amendment (Definition and Religious Freedoms) Bill 2017 on 16/11/17.

**Comment by mlandauer** [comment]
Thanks for spotting the problem. @wwwalker I'm going to take a look at this this afternoon. Sorry for the hassle!

**Comment by mlandauer** [comment]
That's all fixed now. You can see the missing debates have been loaded:
http://www.openaustralia.org.au/senate/?y=2017

It looks like the house of reps didn't sit in that time range. It was just the Senate.
