### ISSUE TITLE
no debates for house or senate from 5 February 2018

### ISSUE THREAD

**Issue by wwwalker** [openaustralia/openaustralia#633]
In

http://www.openaustralia.org.au/hansard/

there are no debates in 2018 even though parliament has started for this year from 5/2/18.

**Comment by MicaelaMicaela** [comment]
Related to this pull request: https://github.com/openaustralia/twfy/pull/21

**Comment by wwwalker** [comment]
This seems to be fixed. I am getting alerts for February 2018 debates and all the debates are there now from February 2018 onwards.

**Comment by wwwalker** [comment]
I got a bumper alert dating back to 7 December 2017 on 28/3/18.

Is this a one off catch up or is there a bug?

**Comment by mlandauer** [comment]
This was one off catch up. Thanks for double checking!
