### ISSUE TITLE
websites.xml is empty/malformed

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/openaustralia#635]
http://data.openaustralia.org.au/members/websites.xml is currently returning (in its entirety):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<peopleinfo>
```

**Comment by jamezpolley** [comment]
Thanks for letting us know about this.

The file has content again now -  it appears to have been solved by adding Patrick Gorman into the list of members.
