### ISSUE TITLE
no debates from August 2018

### ISSUE THREAD

**Issue by wwwalker** [openaustralia/openaustralia#636]
In https://www.openaustralia.org.au/hansard/

there are only debates up to June 2018.

It is missing debates in August 2018 including from Susan Lamb and Fraser Anning recently.

This happened before in issue 623:

http://github.com/openaustralia/openaustralia/issues/623

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_egfp)

**Comment by jamezpolley** [comment]
Also, from Aug 9:
```
parse-speeche:   0% |                                          | ETA:  --:--:--
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/mechanize-0.9.2/lib/www/mechanize.rb:546:in `fetch_page': 500 => Net::HTTPInternalServerError (WWW::Mechanize::ResponseCodeError)
        from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/mechanize-0.9.2/lib/www/mechanize.rb:229:in `get'
        from ../../openaustralia-parser/lib/mechanize_proxy.rb:136:in `get'
        from ../../openaustralia-parser/lib/mechanize_proxy.rb:21:in `load_and_cache_page'
        from ../../openaustralia-parser/lib/mechanize_proxy.rb:136:in `get'
        from ../../openaustralia-parser/lib/hansard_parser.rb:66:in `unpatched_hansard_xml_source_data_on_date'
        from ../../openaustralia-parser/lib/hansard_parser.rb:85:in `hansard_xml_source_data_on_date'
        from ../../openaustralia-parser/lib/hansard_parser.rb:117:in `hansard_day_on_date'
        from ../../openaustralia-parser/lib/hansard_parser.rb:155:in `parse_date_house'
        from ../../openaustralia-parser/parse-speeches.rb:120
        from ../../openaustralia-parser/parse-speeches.rb:87:in `call'
        from ../../openaustralia-parser/parse-speeches.rb:87:in `parse_with_retry'
        from ../../openaustralia-parser/parse-speeches.rb:122
ERROR While processing representatives 2018-08-08:```

**Comment by jamezpolley** [comment]
Possibly related to #635 ?

**Comment by wwwalker** [comment]
There are only debates from 16 August 2018. Earlier in August are missing.

I got alerts today and found only 16 August 2018 onward was listed.

**Comment by jamezpolley** [comment]
I've finally been able to merge the Patrick Gorman changes, and thus been able to add in all the missing days.

I'm going to optimistically close this now, but please reopen it if anything is still missing.

**Comment by wwwalker** [comment]
There is no speech by Susan Lamb in August yet after she returned from re-election on 15/8/18.

I can't find 'final solution' speech by Fraser Anning on 14/8/18.

**Comment by wwwalker** [comment]
14-15/8/18 speeches are there now but now there are no speeches from 20/8/18 onwards.

Import script is broken again.

**Comment by jamezpolley** [comment]
Hi Dwight!

I've already opened #643 for the issues preventing the speeches from 18th onwards appearing, and it should be fixed after I merge in openaustralia/openaustralia-parser/pull/53

**Comment by jamezpolley** [comment]
The reason for the other speeches not showing in search results turns out to be because I didn't run a re-indexing procedure. I've now documented the procedure so it shouldn't be missed in future.
