### ISSUE TITLE
"Share This" Links don't work in OA

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/openaustralia#650]
OS: Windows 10
Browser: Chrome

When you click the "Share This" button you're redirected but it just tries to share the "AddThis" Link.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_g0ut)

**Comment by jamezpolley** [comment]
In addition, they're broken in Firefox because of being non-https

**Comment by jamezpolley** [comment]
I've updated the links to use https and this is working now for me.
