### ISSUE TITLE
missing debates from 15/10/18 onwards

### ISSUE THREAD

**Issue by wwwalker** [openaustralia/openaustralia#652]
Again there are missing debates this time from 15/10/18.

May be there is another import or parsing error not caught before when this happened.

**Comment by jamezpolley** [comment]
Thanks Dwight. Would you be interested in an invitation to our Slack so you can talk to us about this more directly?

**Comment by jamezpolley** [comment]
In this case - it looks like the problem might be related to openaustralia/publicwhip#1185 - the data is getting through to TVFY (which parses it wrongly) but the OA parser is throwing an error

**Comment by wwwalker** [comment]
Yes just give me your slack URL and I will join your slack.

**Comment by jamezpolley** [comment]
There was a parsing error. Also a full disk, PHP running out of memory, parlinfo being down for a while, monitoring that somehow never got set up.. I think it's all fixed now.

**Comment by wwwalker** [comment]
It appears all debates from 15/10/18 are there now. I don't know if alerts will be caught up. I used RSS search of Longman and there are speeches there from 15/10/18. I joined slack. Thanks.
