### ISSUE TITLE
No data for 2-3 Apr 2019 House or Senate

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/openaustralia#661]
The debates for 2 to 3 April 2019 are not showing up for either the [Senate](https://www.openaustralia.org.au/senate/?y=2019) or the [House](https://www.openaustralia.org.au/debates/?y=2019) on OpenAustralia.

**Comment by jamezpolley** [comment]
```
ERROR HansardParser: 2019-04-02 senate 244276: Unknown speaker Senator SPENDER
../../openaustralia-parser/lib/hansard_parser.rb:197:in `throw': uncaught throw `2019-04-02 senate: Couldn't figure out who Spender, D is in division (voting no)' (NameError)
```

Same on April 3

**Comment by jamezpolley** [comment]
https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=244276

Senator Duncan Spender
Senator for New South Wales
Party: Liberal Democratic Party
Chamber: Senate

Appointed by the Governor of New South Wales on 20.3.2019 under section 15 of the Constitution to represent that State in the Senate, vice D Leyonhjelm (resigned).

**Comment by jamezpolley** [comment]
Spender added in openaustralia/openaustralia-parser/pull/69 and 6e54a56.

**Comment by jamezpolley** [comment]
Deployed to production

**Comment by jamezpolley** [comment]
OA and TVFY updated. TVFY is now working on updating guessed whips etc.
