### ISSUE TITLE
2019 Postcode list can't be loaded

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/openaustralia#663]
````
Reading members data...
./postcodes.rb:29:in `throw': uncaught throw `Constituency Bean not found' (NameError)
        from ./postcodes.rb:29
        from ./postcodes.rb:28:in `each'       
        from ./postcodes.rb:28
````

We'll need to update the list of representatives (and this electorates) before we can update the list of postcodes.

**Comment by jamezpolley** [comment]
@MicaelaMicaela can you assign this back to me once we have the update list of reps?

**Comment by MicaelaMicaela** [comment]
@jamezpolley will do

**Comment by MicaelaMicaela** [comment]
@jamezpolley as requested, I've assigned this back to you as I've just finished the pull request updating the list of reps

**Comment by jamezpolley** [comment]
and this has been sorted.
