### ISSUE TITLE
Make the Foundation's DGR status easier to discover.

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/openaustralia#664]
Related to #500

We had a query last week asking whether openaustralia.org has DGR status.

I thought this was fairly easy to determine from the site, so I went to have a look. The shortest path I found was:

* https://openaustralia.org.au 
* Click on "about us" in the footer
* https://www.openaustralia.org.au/about/
* Click on the "OpenAustralia Foundation" link
* https://www.oaf.org.au/
* Very small wording in the footer: "OpenAustralia Foundation Limited is a charity - company limited by guarantee and endorsed as a deductible gift recipient."

It seems like it would be useful to have the DGR status more directly findable from openaustralia.org.au

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_skat)

**Comment by jamezpolley** [comment]
The footer on oaf.org.au says:

````
© 2019 OpenAustralia Foundation Limited, Level 15, 461 Bourke Street, Melbourne Victoria 3000. ABN [24 138 089 942](http://www.abr.business.gov.au/(2bjbr1rb5qmkdwqjuus0fc55)/search.aspx?StartSearch=True&SearchText=24138089942).
OpenAustralia Foundation Limited is a charity - company limited by guarantee and endorsed as a deductible gift recipient.
````
Perhaps this wording would be useful everywhere?

**Comment by mlandauer** [comment]
Also DGR status is only relevant if you're donating. So it should be very clear when you're donating. I think we do a pretty good job of this generally. So, I don't think this is a problem.
