### ISSUE TITLE
stop spammy comment reports

### ISSUE THREAD

**Issue by katska** [openaustralia/openaustralia#674]
We are getting an increasing number of spam on a specific comment. It's a daily bore to delete these as they increase. 

'A new comment report has been filed by James Smith. 

COMMENT: 
Government books aren't balanced when you are in surplus. 

With a surplus, government revenue outpaces the rate it is spending that money. With a deficit the government spends more than it collects. 

Perhaps that's too simplistic, but the LNP often likes to compare government budgeting with household budgeting to help us simple folk understand such a complex issue. 

The Opposition is not the only group who don't know the definition of a surplus, it seems. 

REPORT: 
Muchas gracias. ?Como puedo iniciar sesion? 

To manage this report follow this link: http://openaustralia.org.au/admin/report.php?ridV9&cid52 
'

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_37k1x)

**Comment by mlandauer** [comment]
As I've mentioned before I think we should just disable comments (and once things settle down comment reports as well). Comments are not serving much of a purpose and are not really consistent with what the rest of the site is trying to achieve and cause us problems in terms of maintenance...

**Comment by mlandauer** [comment]
We actually did this a while ago
