### ISSUE TITLE
tell people who have commented that the commenting is closed now

### ISSUE THREAD

**Issue by katska** [openaustralia/openaustralia#679]
Because we're removing user comments, we should let people know who have used this facility in the past.

Dear PERSON

I’m writing to you today because you made at least one comment on openaustralia.org.au in response to a speech one of our elected representatives made. I want to personally thank you for speaking up for something you feel strongly enough about in this way. 

Today we removed the ability to comment on speeches published at openaustralia.org.au

We’re pausing this facility, the ability to make comments on OpenAustralia because, in our work we want to make it a little easier for people who want to make a difference to have their voices heard, and for their voices to matter in the collective decision making we call democracy. 

The commenting facility takes work to maintain, and the disappointing truth is there are very few people who have used it. Maybe that means we're not providing a facility people want, or that we’ve not provided quite the right way to do it. One piece that's certainly missing for us, is that we don't really know what happens to comments once they're made. Did you receive any response or other follow up by the elected representative, their staff or anyone else?

To help us decide what to do in the future, as someone who has made a comment here, we would like to learn something about your experience of commenting.

Would you be willing to say a little about your experience of making a comment on openaustralia.org.au, either by responding to this email, or if they are willing to have a short conversation by phone._

For the time being, any comment you made before will remain visible, at least the next few months. In the meantime, we’ll regroup and make decisions about whether commenting could play a role in the future direction of openaustralia.org.au 

Warm Regards, 
Katherine Szuminska
On behalf of the Directors of the OpenAustralia Foundation

prompted by #678

**Comment by katska** [comment]
@mlandauer  I welcome your comments and also - how do we send this out? I've expanded some details and I think it's pretty close to being good to go.
Do you think a variant of this would work as a short blog post. prefer to send as yourself (and you can refer them to me for the chat, or forward interest).

**Comment by katska** [comment]
I've looked at openaustralia.org.au admin but am not able to see the email addresses of users who have commented if their addresses are not public. eg https://www.openaustralia.org.au/user/?u=4152 I'm going to see if I can find them in cuttlefish

**Comment by mlandauer** [comment]
> I've looked at openaustralia.org.au admin but am not able to see the email addresses of users who have commented if their addresses are not public. eg https://www.openaustralia.org.au/user/?u=4152 I'm going to see if I can find them in cuttlefish

In that case you could collect the user id's of all the people you need to find the email address for and then I could do a database query to get them. How does that sound @katska?

**Comment by katska** [comment]
Thank you, that would help if you have time. I'm feeling good about publishing a post too. 

In doing this task I'm also wondering what else would give this experiment greater value, both for OAF and for the people who have taken the time to comment over the years.

**Comment by katska** [comment]
@matthew by user id I think that's the numeric code of the user. Collecting the names from comments is already turned into quite a big time suck, so I think I might just stick to the blog post. Let's see how I get on.

**Comment by mlandauer** [comment]
@katska If you look at https://www.openaustralia.org.au/admin/comments.php you can see all the recent comments. Just the first page of the results gives you everyone who has commented in the last year. Doing that limits it to people who it's likely to be relevant for?

**Comment by mlandauer** [comment]
Actually you get the same list at https://www.openaustralia.org.au/comments/recent/

**Comment by katska** [comment]
[ Here's a list](https://docs.google.com/document/d/1n2Skc2L3soFVXiIFUEQdC0hqOCPRMy-M5k9jWTe_-y8/edit) of published names to thank, from the published names of people who [commented on OpenAustralia](https://www.openaustralia.org.au/comments/recent) - I did remove a couple, due to being either spam or abusive commenters that previously fell through the cracks.

**Comment by katska** [comment]
Since I wasn't able to access email addresses and it was a long time ago, I'm closing now. Too hard. We did already express gratitude on the blog which I'm going to say is good enough at this point.
